//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebserviceFileSystem.Uploader {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] dataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Uploader.FileUploaderSoap")]
    public interface FileUploaderSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 f 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        WebserviceFileSystem.Uploader.UploadFileResponse UploadFile(WebserviceFileSystem.Uploader.UploadFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileSearchPattern 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadFile", ReplyAction="*")]
        WebserviceFileSystem.Uploader.DownloadFileResponse DownloadFile(WebserviceFileSystem.Uploader.DownloadFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileSearchPattern 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        WebserviceFileSystem.Uploader.ListResponse List(WebserviceFileSystem.Uploader.ListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 oldFileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Move", ReplyAction="*")]
        WebserviceFileSystem.Uploader.MoveResponse Move(WebserviceFileSystem.Uploader.MoveRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        WebserviceFileSystem.Uploader.RemoveResponse Remove(WebserviceFileSystem.Uploader.RemoveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(WebserviceFileSystem.Uploader.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] f, string fileName) {
            this.f = f;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(WebserviceFileSystem.Uploader.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadFile", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.DownloadFileRequestBody Body;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(WebserviceFileSystem.Uploader.DownloadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileSearchPattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dirSearchPattern;
        
        public DownloadFileRequestBody() {
        }
        
        public DownloadFileRequestBody(string fileSearchPattern, string dirSearchPattern) {
            this.fileSearchPattern = fileSearchPattern;
            this.dirSearchPattern = dirSearchPattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.DownloadFileResponseBody Body;
        
        public DownloadFileResponse() {
        }
        
        public DownloadFileResponse(WebserviceFileSystem.Uploader.DownloadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebserviceFileSystem.Uploader.FileItem[] DownloadFileResult;
        
        public DownloadFileResponseBody() {
        }
        
        public DownloadFileResponseBody(WebserviceFileSystem.Uploader.FileItem[] DownloadFileResult) {
            this.DownloadFileResult = DownloadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(WebserviceFileSystem.Uploader.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileSearchPattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dirSearchPattern;
        
        public ListRequestBody() {
        }
        
        public ListRequestBody(string fileSearchPattern, string dirSearchPattern) {
            this.fileSearchPattern = fileSearchPattern;
            this.dirSearchPattern = dirSearchPattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(WebserviceFileSystem.Uploader.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebserviceFileSystem.Uploader.ArrayOfString ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(WebserviceFileSystem.Uploader.ArrayOfString ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Move", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.MoveRequestBody Body;
        
        public MoveRequest() {
        }
        
        public MoveRequest(WebserviceFileSystem.Uploader.MoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string oldFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newFileName;
        
        public MoveRequestBody() {
        }
        
        public MoveRequestBody(string oldFileName, string newFileName) {
            this.oldFileName = oldFileName;
            this.newFileName = newFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.MoveResponseBody Body;
        
        public MoveResponse() {
        }
        
        public MoveResponse(WebserviceFileSystem.Uploader.MoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MoveResult;
        
        public MoveResponseBody() {
        }
        
        public MoveResponseBody(string MoveResult) {
            this.MoveResult = MoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(WebserviceFileSystem.Uploader.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebserviceFileSystem.Uploader.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(WebserviceFileSystem.Uploader.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(string RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileUploaderSoapChannel : WebserviceFileSystem.Uploader.FileUploaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileUploaderSoapClient : System.ServiceModel.ClientBase<WebserviceFileSystem.Uploader.FileUploaderSoap>, WebserviceFileSystem.Uploader.FileUploaderSoap {
        
        public FileUploaderSoapClient() {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileUploaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebserviceFileSystem.Uploader.UploadFileResponse WebserviceFileSystem.Uploader.FileUploaderSoap.UploadFile(WebserviceFileSystem.Uploader.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] f, string fileName) {
            WebserviceFileSystem.Uploader.UploadFileRequest inValue = new WebserviceFileSystem.Uploader.UploadFileRequest();
            inValue.Body = new WebserviceFileSystem.Uploader.UploadFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            WebserviceFileSystem.Uploader.UploadFileResponse retVal = ((WebserviceFileSystem.Uploader.FileUploaderSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebserviceFileSystem.Uploader.DownloadFileResponse WebserviceFileSystem.Uploader.FileUploaderSoap.DownloadFile(WebserviceFileSystem.Uploader.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public WebserviceFileSystem.Uploader.FileItem[] DownloadFile(string fileSearchPattern, string dirSearchPattern) {
            WebserviceFileSystem.Uploader.DownloadFileRequest inValue = new WebserviceFileSystem.Uploader.DownloadFileRequest();
            inValue.Body = new WebserviceFileSystem.Uploader.DownloadFileRequestBody();
            inValue.Body.fileSearchPattern = fileSearchPattern;
            inValue.Body.dirSearchPattern = dirSearchPattern;
            WebserviceFileSystem.Uploader.DownloadFileResponse retVal = ((WebserviceFileSystem.Uploader.FileUploaderSoap)(this)).DownloadFile(inValue);
            return retVal.Body.DownloadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebserviceFileSystem.Uploader.ListResponse WebserviceFileSystem.Uploader.FileUploaderSoap.List(WebserviceFileSystem.Uploader.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public WebserviceFileSystem.Uploader.ArrayOfString List(string fileSearchPattern, string dirSearchPattern) {
            WebserviceFileSystem.Uploader.ListRequest inValue = new WebserviceFileSystem.Uploader.ListRequest();
            inValue.Body = new WebserviceFileSystem.Uploader.ListRequestBody();
            inValue.Body.fileSearchPattern = fileSearchPattern;
            inValue.Body.dirSearchPattern = dirSearchPattern;
            WebserviceFileSystem.Uploader.ListResponse retVal = ((WebserviceFileSystem.Uploader.FileUploaderSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebserviceFileSystem.Uploader.MoveResponse WebserviceFileSystem.Uploader.FileUploaderSoap.Move(WebserviceFileSystem.Uploader.MoveRequest request) {
            return base.Channel.Move(request);
        }
        
        public string Move(string oldFileName, string newFileName) {
            WebserviceFileSystem.Uploader.MoveRequest inValue = new WebserviceFileSystem.Uploader.MoveRequest();
            inValue.Body = new WebserviceFileSystem.Uploader.MoveRequestBody();
            inValue.Body.oldFileName = oldFileName;
            inValue.Body.newFileName = newFileName;
            WebserviceFileSystem.Uploader.MoveResponse retVal = ((WebserviceFileSystem.Uploader.FileUploaderSoap)(this)).Move(inValue);
            return retVal.Body.MoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebserviceFileSystem.Uploader.RemoveResponse WebserviceFileSystem.Uploader.FileUploaderSoap.Remove(WebserviceFileSystem.Uploader.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public string Remove(string fileName) {
            WebserviceFileSystem.Uploader.RemoveRequest inValue = new WebserviceFileSystem.Uploader.RemoveRequest();
            inValue.Body = new WebserviceFileSystem.Uploader.RemoveRequestBody();
            inValue.Body.fileName = fileName;
            WebserviceFileSystem.Uploader.RemoveResponse retVal = ((WebserviceFileSystem.Uploader.FileUploaderSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
    }
}
