//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5448.
// 
namespace cardocr_mobile6.uploaderWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FileUploaderSoap", Namespace="http://tempuri.org/")]
    public partial class FileUploader : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public FileUploader() {
            //sdcc:
            //this.Url = "http://13.187.242.140/mb/FileUploader.asmx";
            //home:
            this.Url = "http://192.168.72.130/mb/FileUploader.asmx";
            //bad:this.Url = "http://192.168.72.1:21369/mb/FileUploader.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadFile(System.Guid sessionID, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, string fileName) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        sessionID,
                        f,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadFile(System.Guid sessionID, byte[] f, string fileName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadFile", new object[] {
                        sessionID,
                        f,
                        fileName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUploadFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileContent[] DownloadFile(System.Guid sessionID, string fileSearchPattern, string dirSearchPattern) {
            object[] results = this.Invoke("DownloadFile", new object[] {
                        sessionID,
                        fileSearchPattern,
                        dirSearchPattern});
            return ((FileContent[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDownloadFile(System.Guid sessionID, string fileSearchPattern, string dirSearchPattern, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DownloadFile", new object[] {
                        sessionID,
                        fileSearchPattern,
                        dirSearchPattern}, callback, asyncState);
        }
        
        /// <remarks/>
        public FileContent[] EndDownloadFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FileContent[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] List(System.Guid sessionID, string fileSearchPattern, string dirSearchPattern) {
            object[] results = this.Invoke("List", new object[] {
                        sessionID,
                        fileSearchPattern,
                        dirSearchPattern});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginList(System.Guid sessionID, string fileSearchPattern, string dirSearchPattern, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("List", new object[] {
                        sessionID,
                        fileSearchPattern,
                        dirSearchPattern}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Move", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Move(System.Guid sessionID, string oldFileName, string newFileName) {
            object[] results = this.Invoke("Move", new object[] {
                        sessionID,
                        oldFileName,
                        newFileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMove(System.Guid sessionID, string oldFileName, string newFileName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Move", new object[] {
                        sessionID,
                        oldFileName,
                        newFileName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndMove(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Remove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Remove(System.Guid sessionID, string fileName) {
            object[] results = this.Invoke("Remove", new object[] {
                        sessionID,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRemove(System.Guid sessionID, string fileName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Remove", new object[] {
                        sessionID,
                        fileName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRemove(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartSession(System.Guid sessionID, string clientID) {
            this.Invoke("StartSession", new object[] {
                        sessionID,
                        clientID});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStartSession(System.Guid sessionID, string clientID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StartSession", new object[] {
                        sessionID,
                        clientID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndStartSession(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMessage(System.Guid sessionID, Message msg) {
            this.Invoke("SendMessage", new object[] {
                        sessionID,
                        msg});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendMessage(System.Guid sessionID, Message msg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendMessage", new object[] {
                        sessionID,
                        msg}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSendMessage(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StopSession", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StopSession(System.Guid sessionID) {
            this.Invoke("StopSession", new object[] {
                        sessionID});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStopSession(System.Guid sessionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StopSession", new object[] {
                        sessionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndStopSession(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetMessageResult GetMessage(System.Guid sessionID) {
            object[] results = this.Invoke("GetMessage", new object[] {
                        sessionID});
            return ((GetMessageResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMessage(System.Guid sessionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMessage", new object[] {
                        sessionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetMessageResult EndGetMessage(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetMessageResult)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileContent {
        
        private string path_Field;
        
        private byte[] content_Field;
        
        /// <remarks/>
        public string path_ {
            get {
                return this.path_Field;
            }
            set {
                this.path_Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] content_ {
            get {
                return this.content_Field;
            }
            set {
                this.content_Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageResult {
        
        private bool _DoneField;
        
        private string[] _ClientIDsField;
        
        private Message[] _MessagesField;
        
        /// <remarks/>
        public bool _Done {
            get {
                return this._DoneField;
            }
            set {
                this._DoneField = value;
            }
        }
        
        /// <remarks/>
        public string[] _ClientIDs {
            get {
                return this._ClientIDsField;
            }
            set {
                this._ClientIDsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] _Messages {
            get {
                return this._MessagesField;
            }
            set {
                this._MessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message {
        
        private string fromSessionIDField;
        
        private string fromField;
        
        private string toSessionIDField;
        
        private string toField;
        
        private string dataField;
        
        /// <remarks/>
        public string FromSessionID {
            get {
                return this.fromSessionIDField;
            }
            set {
                this.fromSessionIDField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string ToSessionID {
            get {
                return this.toSessionIDField;
            }
            set {
                this.toSessionIDField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
}
